### create a flight
POST localhost:8001/api/v1/flights
Content-Type: application/json
Authorization: Bearer {{keycloak.access_token}}

{

  "airplaneId" : 1,

  "number" : "AA144",

  "departureAirportCode" : "DUB",

  "arrivalAirportCode" : "FRA",

  "departureDateTime" : "2025-07-15 00:12",

  "arrivalDateTime" : "2025-07-15 05:00",

  "price" : 15.99

}

### find all flights
GET localhost:8001/api/v1/flights

### find flight by number
GET localhost:8001/api/v1/flights/AA144

### update flight
PUT localhost:8001/api/v1/flights
Content-Type: application/json
Authorization: Bearer {{keycloak.access-token}}

{

  "airplaneId" : 2,

  "number" : "AA133",

  "departureAirportCode" : "FRA",

  "arrivalAirportCode" : "DUB",

  "departureDateTime" : "2025-07-15 00:44",

  "arrivalDateTime" : "2025-07-15 05:44",

  "price" : 10.99

}

### create a flight
POST localhost:8001/api/v1/flights
Content-Type: application/json
Authorization: Bearer {{keycloak.access-token}}

{

  "airplaneId" : 1,

  "number" : "AA403",

  "departureAirportCode" : "GYD",

  "arrivalAirportCode" : "BUD",

  "departureDateTime" : "2025-11-15 00:12",

  "arrivalDateTime" : "2025-11-15 05:00",

  "price" : 15.99

}

### delete flight by number
DELETE localhost:8001/api/v1/flights/AA133
Authorization: Bearer {{keycloak.access-token}}

### request app info
GET localhost:8001/app/info
Authorization: Bearer {{keycloak.access-token}}

### request actuator refresh
POST localhost:8001/actuator/refresh

### request actuator health
GET localhost:8001/actuator/health

### request actuator liveness check
GET localhost:8001/actuator/health/liveness

### request actuator metrics
GET localhost:8001/actuator/metrics

### request actuator "jvm.memory.used" metrics
GET localhost:8001/actuator/metrics/jvm.memory.used

### request actuator metrics in OpenMetrics format
GET localhost:8001/actuator/prometheus

### request actuator Liquibase migrations
GET localhost:8001/actuator/liquibase
