### authenticate via keycloak
POST localhost:8080/realms/travel-booking-system/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

#client_id={{keycloak.client-id}}&client_secret={{keycloak.client-secret}}&grant_type=client_credentials
client_id={{keycloak.client-id}}&client_secret={{keycloak.client-secret}}&grant_type=password&username={{keycloak.username-employee}}&password={{keycloak.password-employee}}
